function D=Matriz_D(E,nu,PlaneState)

if PlaneState==0 % ==> Plane Strain
    D=E/((1+nu)*(1-2*nu))*[...
        1-nu , nu   , 0          ;...
        nu   , 1-nu , 0          ;...
        0    , 0    , (1-2*nu)/2]; %D matrix for plane strain
else   % ==> Plane Stress
    D=E/(1-nu^2)*[...
        1  , nu   , 0          ;...
        nu , 1    , 0          ;...
        0  , 0    , (1-nu)/2]; %D matrix for plane stress
end

