function [N,dNxi,dNeta]=shape_f_2d(Coor,Grado,NladosElem,dN_is_calculated)
% =========================================================================
% funciones de forma y derivadas en un punto para triangulos y 
% cuadrilateros en coordenadas locales x=xi y y=eta
% =========================================================================
% IMPORTANTE: en la numeracion de nodos, los nodos 
% vertice son los primeros. Despues de estos se numeran
% los nodos de mitad de lado.
%
% Coor       = coordenadas (X=xi e Y=eta)
% Grado      = Grado del elemento
% NladosElem = Num de Nlados del elem (1, 3 � 4)
% dN_is_calculated      = indicador de calculo de dN 
%                 0    ==> no se calcula
%                 else ==> se calcula la derivada
% SALIDA
%   N        = Matriz de funciones de forma. Cada fila corresponde
%              a las funciones de forma en un punto de coord (x,y)
%   dNxi    = Derivada de matrices de funciones de forma respecto a xi
%   dNeta    = Derivada de matrices de funciones de forma respecto a eta


if nargin==3
    dN_is_calculated=0;
end
    
X=Coor(:,1)';
Y=Coor(:,2)';

switch NladosElem
    
case 3 % TRIANGULOS -----------------------------  
   switch Grado
   case 1 %Triangulos lineales
      N=[...
            1-X-Y;...
            X;...
            Y];
      if dN_is_calculated==0
         dN=0;
      else
         dN=[...
               -1+0.*X,-1+0.*X;...  % 0.*X se usa para mantener el tamaño del vector
               +1+0.*X, 0+0.*X;...
               0+0.*X, 1+0.*X];
      end
   
   case 2 %Triangulos cuadraticos
      N=[...
            (1-X-Y).*(1-2*X-2*Y);...
            -X.*(1-2*X);...
            -Y.*(1-2*Y);...
            4*X.*(1-X-Y);...
            4*X.*Y;...
            4*Y.*(1-X-Y)];
      if dN_is_calculated==0
         dN=0;
      else
         dN=[...
                -1*(1-2*X-2*Y) + (1-X-Y)*-2 , -1*(1-2*X-2*Y) + (1-X-Y)*-2 ;...
                -1*(1-2*X) + -X*-2          , X*0                           ;...
                X*0                         , -1*(1-2*Y) + -Y*-2          ;...
                4*(1-X-Y) + 4*X*-1          , 4*X*-1                      ;...
                4*Y                         , 4*X                         ;...
                4*Y*-1                      , 4*(1-X-Y) + 4*Y*-1         ];
      end
     
      
   otherwise %Triangulos de grado superior
      disp(['Grado polinomico ' num2str(Grado)...
            'No programado para triangulos']);
      error('parando');
   end
case 4 % CUADRILATEROS--------------------------------   
   switch Grado
   case 1  %Cuadrilateros lineales
      N=[...
            (1-Y).*(1-X)/4;...
            (1-Y).*(1+X)/4;...
            (1+Y).*(1+X)/4;...
            (1+Y).*(1-X)/4];
      if dN_is_calculated==0
         dN=0; 
      else
         dN=[...
               (-1+Y)/4, (-1+X)/4;...
               (+1-Y)/4, (-1-X)/4;...
               (+1+Y)/4, (+1+X)/4;...
               (-1-Y)/4, (+1-X)/4];
      end
      
   case 2  %Cuadrilateros cuadraticos
      N=[...
            -(1-Y).*(1-X).*(1+X+Y)/4;...
            -(1-Y).*(1+X).*(1-X+Y)/4;...
            -(1+Y).*(1+X).*(1-X-Y)/4;...
            -(1+Y).*(1-X).*(1+X-Y)/4;...
            (1-X.^2).*(1-Y)/2;...
            (1-Y.^2).*(1+X)/2;...
            (1-X.^2).*(1+Y)/2;...
            (1-Y.^2).*(1-X)/2];...
      if dN_is_calculated==0
         dN=0; 
      else
         dN=[...
            -(1-Y).*( (1-X) + -(1+X+Y))/4, -(1-X).*( (1-Y) + -(1+X+Y))/4;...
            -(1-Y).*(-(1+X) +  (1-X+Y))/4, -(1+X).*( (1-Y) + -(1-X+Y))/4;...
            -(1+Y).*(-(1+X) +  (1-X-Y))/4, -(1+X).*(-(1+Y) +  (1-X-Y))/4;...
            -(1+Y).*( (1-X) + -(1+X-Y))/4, -(1-X).*(-(1+Y) +  (1+X-Y))/4;...
             (-2*X).*(1-Y)/2, (1-X.^2)*-1/2;...
             (1-Y.^2)* 1/2, (-2*Y).*(1+X)/2;...
             (-2*X).*(1+Y)/2, (1-X.^2)* 1/2;...
             (1-Y.^2)*-1/2, (-2*Y).*(1-X)/2];...
      end
            
	otherwise %Cuadrilateros de grado superior
      disp(['Grado polinomico ' num2str(Grado)...
            'No programado para cuadrilateros']);
      error('parando');
   end
otherwise
   disp (['Se ha especificado un elemento de ',num2str(NladosElem),' Nlados']);
   error('parando');
   
end 

N=N';
dN=dN';
  
if dN_is_calculated ==0
    dNxi=[];
    dNeta=[];
else 
    dNxi=dN(1:size(Coor,1),:);
    dNeta=dN(size(Coor,1)+1:end,:);
end
  
return;